name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Setup PNPM
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.5.4
          run_install: |
            - args: [--frozen-lockfile, --silent]

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
